import type { Song, Album } from "./store"

export const mockSongs: Song[] = [
  {
    id: "1",
    title: "Midnight Dreams",
    artist: "Luna Eclipse",
    coverArt: "/midnight-dreams-album-cover.png",
    price: 1.99,
    genre: "electronic",
    rating: 4.5,
    popularity: 95,
    reviews: [
      { user: "MusicLover23", rating: 5, comment: "Absolutely amazing track! The beats are incredible." },
      { user: "SoundWave", rating: 4, comment: "Great production quality, love the synths." },
    ],
  },
  {
    id: "2",
    title: "Ocean Waves",
    artist: "Coastal Vibes",
    coverArt: "/album-cover-ocean-waves.png",
    price: 2.49,
    genre: "ambient",
    rating: 4.2,
    popularity: 87,
    reviews: [
      { user: "ChillSeeker", rating: 4, comment: "Perfect for relaxation and meditation." },
      { user: "NatureSounds", rating: 5, comment: "Feels like being at the beach!" },
    ],
  },
  {
    id: "3",
    title: "Electric Storm",
    artist: "Thunder Bolt",
    coverArt: "/placeholder-bvbxg.png",
    price: 1.79,
    genre: "rock",
    rating: 4.8,
    popularity: 92,
    reviews: [
      { user: "RockFan", rating: 5, comment: "This song rocks! Amazing guitar work." },
      { user: "MetalHead", rating: 5, comment: "Pure energy from start to finish!" },
    ],
  },
  {
    id: "4",
    title: "Jazz Café",
    artist: "Smooth Operators",
    coverArt: "/jazz-cafe-album-cover.png",
    price: 2.99,
    genre: "jazz",
    rating: 4.6,
    popularity: 78,
    reviews: [
      { user: "JazzEnthusiast", rating: 5, comment: "Sophisticated and smooth. Love the saxophone!" },
      { user: "VintageVibes", rating: 4, comment: "Takes me back to the golden age of jazz." },
    ],
  },
  {
    id: "5",
    title: "Digital Horizon",
    artist: "Cyber Pulse",
    coverArt: "/album-cover-digital-horizon.png",
    price: 1.99,
    genre: "electronic",
    rating: 4.3,
    popularity: 89,
    reviews: [
      { user: "TechnoFan", rating: 4, comment: "Futuristic sounds that transport you to another world." },
      { user: "EDMlover", rating: 5, comment: "Perfect for dancing! Great beat drops." },
    ],
  },
  {
    id: "6",
    title: "Mountain Echo",
    artist: "Alpine Sounds",
    coverArt: "/placeholder-m2dqb.png",
    price: 2.29,
    genre: "folk",
    rating: 4.4,
    popularity: 73,
    reviews: [
      { user: "NatureLover", rating: 4, comment: "Beautiful acoustic melodies that touch the soul." },
      { user: "FolkFan", rating: 5, comment: "Reminds me of camping trips in the mountains." },
    ],
  },
  {
    id: "7",
    title: "Neon Nights",
    artist: "Retro Wave",
    coverArt: "/neon-nights-album-cover.png",
    price: 1.89,
    genre: "synthwave",
    rating: 4.7,
    popularity: 91,
    reviews: [
      { user: "RetroGamer", rating: 5, comment: "80s vibes done perfectly! Love the nostalgic feel." },
      { user: "SynthLover", rating: 4, comment: "Great production, captures the retro aesthetic." },
    ],
  },
  {
    id: "8",
    title: "Urban Pulse",
    artist: "City Beats",
    coverArt: "/album-cover-urban-pulse.png",
    price: 2.19,
    genre: "hip-hop",
    rating: 4.1,
    popularity: 85,
    reviews: [
      { user: "HipHopHead", rating: 4, comment: "Solid beats and great flow. Street vibes!" },
      { user: "UrbanMusic", rating: 4, comment: "Captures the energy of the city perfectly." },
    ],
  },
  {
    id: "9",
    title: "Starlight Serenade",
    artist: "Celestial Harmony",
    coverArt: "/album-cover-starlight-serenade.png",
    price: 2.79,
    genre: "classical",
    rating: 4.9,
    popularity: 76,
    reviews: [
      { user: "ClassicalFan", rating: 5, comment: "Breathtaking orchestral arrangement. Pure artistry!" },
      { user: "MusicStudent", rating: 5, comment: "Technically brilliant and emotionally moving." },
    ],
  },
  {
    id: "10",
    title: "Sunset Boulevard",
    artist: "Golden Hour",
    coverArt: "/album-cover-sunset-boulevard.png",
    price: 1.99,
    genre: "indie",
    rating: 4.5,
    popularity: 82,
    reviews: [
      { user: "IndieMusic", rating: 5, comment: "Dreamy and atmospheric. Perfect for evening drives." },
      { user: "AlternativeRock", rating: 4, comment: "Unique sound that stands out from the crowd." },
    ],
  },
  {
    id: "11",
    title: "Bass Drop",
    artist: "Heavy Frequency",
    coverArt: "/album-cover-bass-drop.png",
    price: 1.69,
    genre: "dubstep",
    rating: 4.2,
    popularity: 88,
    reviews: [
      { user: "BassHead", rating: 4, comment: "Massive drops! My speakers are shaking!" },
      { user: "EDMFestival", rating: 4, comment: "Perfect for the dance floor. High energy!" },
    ],
  },
  {
    id: "12",
    title: "Acoustic Dreams",
    artist: "Gentle Strings",
    coverArt: "/acoustic-dreams-album-cover.png",
    price: 2.39,
    genre: "acoustic",
    rating: 4.6,
    popularity: 71,
    reviews: [
      { user: "AcousticLover", rating: 5, comment: "Beautiful guitar work. So peaceful and calming." },
      { user: "CoffeeshopVibes", rating: 4, comment: "Perfect background music for studying." },
    ],
  },
]

export const mockAlbums: Album[] = [
  {
    id: "album-1",
    title: "Midnight Collection",
    artist: "Luna Eclipse",
    coverArt: "/placeholder-kgbw4.png",
    price: 12.99,
  },
  {
    id: "album-2",
    title: "Ocean Symphony",
    artist: "Coastal Vibes",
    coverArt: "/placeholder-msqom.png",
    price: 14.99,
  },
  {
    id: "album-3",
    title: "Electric Anthology",
    artist: "Thunder Bolt",
    coverArt: "/placeholder.svg?height=400&width=400",
    price: 11.99,
  },
]
